insert into CURRENCY_EXCHANGE
(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
values(10001,'USD','INR',65,'');

insert into CURRENCY_EXCHANGE
(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
values(10002,'EUR','INR',75,'');

insert into CURRENCY_EXCHANGE
(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
values(10003,'AUD','INR',25,'');
